import React from "react";
import SliderComponent from "@/components/SliderEspacios";

export const metadata = {
  title: "Espacios",
  description: "Generated by create next app",
};

export default function Espacios() {
  return (
    <div>
      <SliderComponent />
    </div>
  );
}
