import React from "react";
import SliderHabitaciones from "@/components/SliderHabitaciones";

export const metadata = {
  title: "Habitaciones",
  description: "Generated by create next app",
};

export default function Habitaciones() {
  return (
    <main>
      <SliderHabitaciones />
    </main>
  );
}
