import SliderHabSmall from "@/components/habitaciones/SliderHabSmall";
import React from "react";

export const metadata = {
  title: "Habitación Estándar",
  description: "Generated by create next app",
};

function HabitacionS() {
  return (
    <main>
      <SliderHabSmall />
    </main>
  );
}

export default HabitacionS;
